<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <UseWPF>true</UseWPF>
    <RootNamespace>Nri.AssetConfigurators.Wpf</RootNamespace>
    <AssemblyName>Nri.AssetConfigurators.Wpf</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nri.AssetConfigurators.Core\Nri.AssetConfigurators.Core.csproj" />
    <ProjectReference Include="..\Nri.Shared\Nri.Shared.csproj" />
    <ProjectReference Include="..\Nri.Ui.Wpf\Nri.Ui.Wpf.csproj" />
  </ItemGroup>
</Project>
