<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <RootNamespace>Nri.Server</RootNamespace>
    <AssemblyName>Nri.Server</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nri.Shared\Nri.Shared.csproj" />
    <PackageReference Include="MongoDB.Driver" Version="2.29.0" />
    <PackageReference Include="System.Text.Json" Version="8.0.5" />
  </ItemGroup>
</Project>
