<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Nri.AdminClient</RootNamespace>
    <AssemblyName>Nri.AdminClient</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nri.Shared\Nri.Shared.csproj" />
    <ProjectReference Include="..\Nri.Ui.Wpf\Nri.Ui.Wpf.csproj" />
    <ProjectReference Include="..\Nri.AssetConfigurators.Core\Nri.AssetConfigurators.Core.csproj" />
    <ProjectReference Include="..\Nri.AssetConfigurators.Wpf\Nri.AssetConfigurators.Wpf.csproj" />
  </ItemGroup>
</Project>
