<Project Sdk="Microsoft.NET.Sdk.WindowsDesktop">
  <PropertyGroup>
    <OutputType>WinExe</OutputType>
    <UseWPF>true</UseWPF>
    <RootNamespace>Nri.Ui.Wpf.Gallery</RootNamespace>
    <AssemblyName>Nri.Ui.Wpf.Gallery</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <ProjectReference Include="..\Nri.Ui.Wpf\Nri.Ui.Wpf.csproj" />
  </ItemGroup>
</Project>
